version: 3
  services:

  webapp:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80

  banco:
    build:
      context: .
    container_name: banco_mysql
    ports:
      - 3306:3306
    vol:
      - datavolume: /var/lib/mysql
